# MODELO DE PREDICCION (CLA)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import wbgapi as wb

In [4]:
# Crear CSV para entrenamiento y modelo
Exp=wb.data.DataFrame(["SP.ADO.TFRT",
"SP.DYN.CBRT.IN",
"SH.XPD.CHEX.GD.ZS",
"SH.XPD.CHEX.PC.CD",
"SP.DYN.TFRT.IN",
"SP.DYN.LE00.IN",
"SP.DYN.IMRT.IN",
"SP.POP.GROW",
"SP.POP.TOTL",
"SH.STA.SUIC.P5",
"NY.GDP.MKTP.KD",
"NY.GDP.MKTP.KN"],["PER","BRA","COL","ARG","CHL","MEX"],range(2010,2020,1))

In [5]:
Exp

                                 YR2010        YR2011        YR2012  \
economy series
ARG     NY.GDP.MKTP.KD     5.527382e+11  5.859243e+11  5.799102e+11
        NY.GDP.MKTP.KN     6.705237e+11  7.107816e+11  7.034860e+11
        SH.STA.SUIC.P5     8.600000e+00  8.500000e+00  9.100000e+00
        SH.XPD.CHEX.GD.ZS  9.445470e+00  9.418216e+00  9.827282e+00
        SH.XPD.CHEX.PC.CD  9.850344e+02  1.208392e+03  1.368423e+03
...                                 ...           ...           ...
PER     SP.DYN.IMRT.IN     1.530000e+01  1.460000e+01  1.390000e+01
        SP.DYN.LE00.IN     7.441000e+01  7.469700e+01  7.498100e+01
        SP.DYN.TFRT.IN     2.546000e+00  2.493000e+00  2.441000e+00
        SP.POP.GROW        8.129260e-01  8.118964e-01  8.251585e-01
        SP.POP.TOTL        2.902768e+07  2.926431e+07  2.950679e+07

                                 YR2013        YR2014        YR2015  \
economy series
ARG     NY.GDP.MKTP.KD     5.938590e+11  5.789376e+11  5.947493e+11
        NY.GDP.MKTP.KN     7.204071e+11  7.023060e+11  7.214871e+11
        SH.STA.SUIC.P5     8.600000e+00  9.300000e+00  8.300000e+00
        SH.XPD.CHEX.GD.ZS  9.780973e+00  9.671291e+00  1.022934e+01
        SH.XPD.CHEX.PC.CD  1.421658e+03  1.286218e+03  1.531484e+03
...                                 ...           ...           ...
PER     SP.DYN.IMRT.IN     1.330000e+01  1.270000e+01  1.220000e+01
        SP.DYN.LE00.IN     7.525800e+01  7.552900e+01  7.579200e+01
        SP.DYN.TFRT.IN     2.394000e+00  2.355000e+00  2.323000e+00
        SP.POP.GROW        9.014653e-01  1.057019e+00  1.256159e+00
        SP.POP.TOTL        2.977399e+07  3.009037e+07  3.047074e+07

                                 YR2016        YR2017        YR2018  \
economy series
ARG     NY.GDP.MKTP.KD     5.823766e+11  5.987909e+11  5.831181e+11
        NY.GDP.MKTP.KN     7.064778e+11  7.263899e+11  7.073774e+11
        SH.STA.SUIC.P5     8.300000e+00  8.900000e+00  9.200000e+00
        SH.XPD.CHEX.GD.ZS  9.001897e+00  1.044226e+01  9.666465e+00
        SH.XPD.CHEX.PC.CD  1.153534e+03  1.529670e+03  1.127928e+03
...                                 ...           ...           ...
PER     SP.DYN.IMRT.IN     1.170000e+01  1.120000e+01  1.070000e+01
        SP.DYN.LE00.IN     7.604400e+01  7.628600e+01  7.651600e+01
        SP.DYN.TFRT.IN     2.297000e+00  2.275000e+00  2.254000e+00
        SP.POP.GROW        1.483157e+00  1.661928e+00  1.718268e+00
        SP.POP.TOTL        3.092604e+07  3.144430e+07  3.198926e+07

                                 YR2019
economy series
ARG     NY.GDP.MKTP.KD     5.713045e+11
        NY.GDP.MKTP.KN     6.930464e+11
        SH.STA.SUIC.P5     8.400000e+00
        SH.XPD.CHEX.GD.ZS  9.510071e+00
        SH.XPD.CHEX.PC.CD  9.459919e+02
...                                 ...
PER     SP.DYN.IMRT.IN     1.030000e+01
        SP.DYN.LE00.IN     7.673600e+01
        SP.DYN.TFRT.IN     2.233000e+00
        SP.POP.GROW        1.616157e+00
        SP.POP.TOTL        3.251046e+07

[72 rows x 10 columns]

In [6]:
Exf=Exp.transpose()

In [7]:
Exf

economy            ARG                                                  \
series  NY.GDP.MKTP.KD NY.GDP.MKTP.KN SH.STA.SUIC.P5 SH.XPD.CHEX.GD.ZS
YR2010    5.527382e+11   6.705237e+11            8.6          9.445470
YR2011    5.859243e+11   7.107816e+11            8.5          9.418216
YR2012    5.799102e+11   7.034860e+11            9.1          9.827282
YR2013    5.938590e+11   7.204071e+11            8.6          9.780973
YR2014    5.789376e+11   7.023060e+11            9.3          9.671291
YR2015    5.947493e+11   7.214871e+11            8.3         10.229339
YR2016    5.823766e+11   7.064778e+11            8.3          9.001897
YR2017    5.987909e+11   7.263899e+11            8.9         10.442255
YR2018    5.831181e+11   7.073774e+11            9.2          9.666465
YR2019    5.713045e+11   6.930464e+11            8.4          9.510071

economy                                                              \
series  SH.XPD.CHEX.PC.CD SP.ADO.TFRT SP.DYN.CBRT.IN SP.DYN.IMRT.IN
YR2010         985.034424     63.3154         18.154           12.9
YR2011        1208.391602     63.4412         18.055           12.4
YR2012        1368.422974     63.5670         17.949           11.9
YR2013        1421.657593     63.4100         17.831           11.3
YR2014        1286.217651     63.2530         17.698           10.8
YR2015        1531.484253     63.0960         17.548           10.2
YR2016        1153.534058     62.9390         17.383            9.7
YR2017        1529.670044     62.7820         17.205            9.2
YR2018        1127.928467     62.5654         17.021            8.6
YR2019         945.991943     62.3488         16.833            8.1

economy                                ...            PER                    \
series  SP.DYN.LE00.IN SP.DYN.TFRT.IN  ... SH.STA.SUIC.P5 SH.XPD.CHEX.GD.ZS
YR2010          75.278          2.346  ...            3.5          4.715487
YR2011          75.439          2.338  ...            3.3          4.533416
YR2012          75.598          2.330  ...            3.2          4.740239
YR2013          75.756          2.322  ...            3.1          4.760352
YR2014          75.913          2.312  ...            2.9          4.978508
YR2015          76.068          2.301  ...            2.7          4.979630
YR2016          76.221          2.288  ...            2.6          4.972741
YR2017          76.372          2.275  ...            2.7          4.917768
YR2018          76.520          2.261  ...            2.8          5.197577
YR2019          76.667          2.247  ...            2.8          5.215069

economy                                                              \
series  SH.XPD.CHEX.PC.CD SP.ADO.TFRT SP.DYN.CBRT.IN SP.DYN.IMRT.IN
YR2010         241.928696     66.0112         20.621           15.3
YR2011         264.885040     64.1646         20.109           14.6
YR2012         309.847382     62.3180         19.617           13.9
YR2013         323.165527     61.2308         19.185           13.3
YR2014         334.687317     60.1436         18.827           12.7
YR2015         312.721710     59.0564         18.544           12.2
YR2016         313.517181     57.9692         18.323           11.7
YR2017         334.823334     56.8820         18.134           11.2
YR2018         365.863831     55.9518         17.949           10.7
YR2019         370.109955     55.0216         17.756           10.3

economy
series  SP.DYN.LE00.IN SP.DYN.TFRT.IN SP.POP.GROW SP.POP.TOTL
YR2010          74.410          2.546    0.812926  29027680.0
YR2011          74.697          2.493    0.811896  29264314.0
YR2012          74.981          2.441    0.825158  29506790.0
YR2013          75.258          2.394    0.901465  29773986.0
YR2014          75.529          2.355    1.057019  30090372.0
YR2015          75.792          2.323    1.256159  30470739.0
YR2016          76.044          2.297    1.483157  30926036.0
YR2017          76.286          2.275    1.661928  31444299.0
YR2018          76.516          2.254    1.718268  31989265.0
YR2019          76.736          2.233    1.616157  32510462.0

[10 rows x 72 columns]

In [8]:
Exf.to_csv("CLA.csv",index=False)

In [9]:
data = pd.read_csv("CLA.csv")

In [26]:
data["ARG"]

0       NY.GDP.MKTP.KD
1     552738161802.463
2     585924294024.785
3     579910247223.428
4     593858966307.156
5     578937574935.696
6     594749285413.212
7      582376550428.09
8     598790850843.677
9     583118120294.002
10    571304530654.919
Name: ARG, dtype: object

In [16]:
#Buscamos si tenemos instancias duplicadas. Esto lo hacemos de la siguiente manera.
data[data.duplicated()]

Empty DataFrame
Columns: [ARG, ARG.1, ARG.2, ARG.3, ARG.4, ARG.5, ARG.6, ARG.7, ARG.8, ARG.9, ARG.10, ARG.11, BRA, BRA.1, BRA.2, BRA.3, BRA.4, BRA.5, BRA.6, BRA.7, BRA.8, BRA.9, BRA.10, BRA.11, CHL, CHL.1, CHL.2, CHL.3, CHL.4, CHL.5, CHL.6, CHL.7, CHL.8, CHL.9, CHL.10, CHL.11, COL, COL.1, COL.2, COL.3, COL.4, COL.5, COL.6, COL.7, COL.8, COL.9, COL.10, COL.11, MEX, MEX.1, MEX.2, MEX.3, MEX.4, MEX.5, MEX.6, MEX.7, MEX.8, MEX.9, MEX.10, MEX.11, PER, PER.1, PER.2, PER.3, PER.4, PER.5, PER.6, PER.7, PER.8, PER.9, PER.10, PER.11]
Index: []

[0 rows x 72 columns]